version: "3"

services:
    mongo:
      image: mongo
      restart: always
      ports:
        - 27027:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
      - "./dump:/dumps"


    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password


    db:
      image: mysql:8.0.22
      container_name: "MySQL_DB"
      ports:
        - "33006:3306"
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: spareparts