version: "3"

services:
  db:
    image: mysql:8.0.22
    container_name: "MySQL_DB"
    ports:
      - "33006:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spareparts
